# Generated by Django 5.1.3 on 2025-01-24 09:39

import apps.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('config', models.JSONField(default=dict, validators=[apps.common.models.ConfigSchema.validate_schema])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
