# Generated by Django 5.1.3 on 2025-03-11 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('version', models.IntegerField(choices=[(1, '1')], default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Failed')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TxInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('vout', models.PositiveIntegerField()),
                ('script_sig', models.TextField(blank=True, null=True)),
                ('prev_tx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.txinput')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='blockchain.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TxOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('value', models.BigIntegerField()),
                ('script_pub_key', models.TextField(help_text='the target wallet public key')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='blockchain.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
