# Generated by Django 5.1.3 on 2025-03-13 16:57

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_account_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(choices=[(1, 'V1')], default=1)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Failed')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FiatTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('value', models.DecimalField(decimal_places=10, max_digits=30)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Failed')], default=0)),
                ('metadata', models.JSONField(default=dict)),
                ('kind', models.BooleanField(choices=[(0, 'withdraw'), (1, 'deposit')])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='users.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='blockchain.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TxOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('value', models.DecimalField(decimal_places=10, max_digits=30)),
                ('script_pub_key', models.TextField(db_index=True, help_text='the target wallet public key')),
                ('spent', models.BooleanField(default=False)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outputs', to='blockchain.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='TxInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('script_sig', models.TextField(blank=True, null=True)),
                ('prev_tx', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prev_outputs', to='blockchain.transaction')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='blockchain.transaction')),
                ('vout', models.ForeignKey(help_text='Output index from previous transaction', on_delete=django.db.models.deletion.PROTECT, to='blockchain.txoutput')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='txoutput',
            index=django.contrib.postgres.indexes.HashIndex(fields=['script_pub_key'], name='blockchain__script__d6277e_hash'),
        ),
    ]
