# Generated by Django 5.1.3 on 2025-03-11 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txinput',
            name='prev_tx',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchain.txinput'),
        ),
    ]
