# Generated by Django 5.1.3 on 2025-03-14 08:03

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_alter_fiattransaction_transaction'),
        ('users', '0005_account_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiattransaction',
            name='tracking_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fiattransaction',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='blockchain.transaction'),
        ),
        migrations.AddIndex(
            model_name='fiattransaction',
            index=django.contrib.postgres.indexes.HashIndex(fields=['tracking_code'], name='blockchain__trackin_8bcd9e_hash'),
        ),
    ]
