# Generated by Django 5.1.3 on 2025-03-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_fiattransaction_tracking_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiattransaction',
            name='spent',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
