# Generated by Django 5.1.3 on 2025-03-12 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_alter_txinput_prev_tx_alter_txinput_vout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='txoutput',
            name='spent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='txinput',
            name='vout',
            field=models.ForeignKey(help_text='Output index from previous transaction', on_delete=django.db.models.deletion.PROTECT, to='blockchain.txoutput'),
        ),
    ]
