# Generated by Django 5.1.3 on 2025-03-12 09:03

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_txoutput_spent_alter_txinput_vout'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='txoutput',
            index=django.contrib.postgres.indexes.HashIndex(fields=['script_pub_key'], name='blockchain__script__d6277e_hash'),
        ),
    ]
