# Generated by Django 5.1.3 on 2025-03-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_txoutput_blockchain__script__d6277e_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='txoutput',
            name='script_pub_key',
            field=models.TextField(db_index=True, help_text='the target wallet public key'),
        ),
    ]
