# Generated by Django 5.1.3 on 2025-03-12 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0006_remove_transaction_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txinput',
            name='prev_tx',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prev_outputs', to='blockchain.txoutput'),
        ),
    ]
