# Generated by Django 5.1.3 on 2025-03-12 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0007_alter_txinput_prev_tx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txinput',
            name='prev_tx',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prev_outputs', to='blockchain.transaction'),
        ),
    ]
