# Generated by Django 5.1.3 on 2025-03-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0008_alter_txinput_prev_tx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txoutput',
            name='value',
            field=models.PositiveBigIntegerField(),
        ),
    ]
