# Generated by Django 5.1.3 on 2025-03-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0009_alter_txoutput_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='version',
            field=models.PositiveIntegerField(choices=[(1, '1')], default=1),
        ),
    ]
