# Generated by Django 5.1.3 on 2025-03-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0010_alter_transaction_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Failed')], default=0),
        ),
    ]
