# Generated by Django 5.1.3 on 2025-03-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0011_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='version',
            field=models.PositiveIntegerField(choices=[(1, 'V1')], default=1),
        ),
    ]
