# Generated by Django 5.1.3 on 2025-03-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank_account',
            field=models.CharField(default='2342346346', max_length=255),
            preserve_default=False,
        ),
    ]
